### ISSUE TITLE
Doesn't look right on iPhone

### ISSUE THREAD

**Issue by dmmikkel** [drgullin/icheck#100]
See screenshot. Tested on iPhone 5.

![screen shot 2013-12-11 at 5 00 46 pm](https://f.cloud.github.com/assets/1391355/1725268/704709b6-627d-11e3-90bc-c00a3d0d2bdb.png)

**Comment by ambasador** [comment]
i switched to jquery ui button, cos its easier to do something and triggers are working ok

**Comment by drgullin** [comment]
That's an issue of your CSS, especially, the retina-related styles.
