### ISSUE TITLE
Full width margin bumping down label

### ISSUE THREAD

**Issue by zreese** [drgullin/icheck#101]
I'm using iCheck with Bootstrap 3 and the checkboxes all have a large margin applied to the right of the checkbox, forcing the label to the next line. Here's what Chrome sees:

![image](https://f.cloud.github.com/assets/5454454/1736779/5f733952-6368-11e3-92eb-0875125b0f4f.png)

I've tried hardcoding a margin-right value of 0 but it keeps being overwritten by... something. I'm not sure why this is happening. I can't find any CSS conflicts from Bootstrap.

**Comment by drgullin** [comment]
That's because of the `display: block` property on styled checkboxes. Try to replace it with `display: inline-block`.

You may also need to set `display: inline` for your labels.

**Comment by sarveshkushwaha** [comment]
Thanks @fronteed its worked :) :+1:
