### ISSUE TITLE
Label and input are not on the same line

### ISSUE THREAD

**Issue by shkup** [drgullin/icheck#102]
I try every possible combination but the input and label are always at seperated lines.
I have cleared the site css, tried both minimal and color scheme but it always appears to be on seperated lines.

Script:

<script src="@Url.Content("~/Scripts/jquery.icheck.js")" type="text/javascript"></script>

```
    <link href="~/Content/iCheck/minimal.css" rel="stylesheet" />

    <script type="text/javascript">

        $(document).ready(function () {
            $('#cbTest').iCheck({
                checkboxClass: 'icheckbox_minimal'
            });

            $('#foo').iCheck({
                checkboxClass: 'icheckbox_minimal'
            });

        });
    </script>
```

HTML:
<label style="display:inline-block">
                <input type="checkbox" id="cbTest" />
                Set contact person
            </label>

```
        <label>
```

  <input type="checkbox"> Check me out
</label>

```
        <label>
          <input type="checkbox" id="foo" />
          <label for="foo">Bar</label>
        </label>
```

Only regular checkbox looks as it should be.

**Comment by mtmail** [comment]
Did you try the display:inline-block solution described in https://github.com/fronteed/iCheck/issues/88 ?

**Comment by shkup** [comment]
yes of course

Date: Tue, 17 Dec 2013 08:43:31 -0800

**Comment by shkup** [comment]
By the way it happens on IE8
