### ISSUE TITLE
Hello, I am using zepto library, but encountered an error.

### ISSUE THREAD

**Issue by tudousi** [drgullin/icheck#105]
Such errors are

Uncaught TypeError: Cannot read property 'uncheckedCheckboxClass' of undefined

**Comment by drgullin** [comment]
This doesn't happen in v1.0.1

Also, make sure you've included polyfill, event and data modules.
https://github.com/madrobby/zepto#zepto-modules

**Comment by horatio-sans-serif** [comment]
polyfill?

**Comment by drgullin** [comment]
It seems that Zepto has changed module names.
By now, likely only one extra module is required - data.

**Comment by Megasu** [comment]
I use Zepto v1.1.6 
add zepto.data.js module is okay.
https://github.com/madrobby/zepto/blob/master/src/data.js

Suggest  add an obvious tips to the readme.
