### ISSUE TITLE
Checkboxes not displaying when emulating IE7 in IE11.

### ISSUE THREAD

**Issue by MrGeneric** [drgullin/icheck#106]
I've just upgraded from 0.9.1 to 1.0.1 and running through a quick browser test in IE11 I noticed the checkboxes no longer display when the document mode is set to IE7.

I don't have a way to run IE7 at the moment, and I was hoping that it's maybe an issue with the emulation.

Has anyone else run into this, or can verify if this issue is unique to me?

Thanks.

**Comment by drgullin** [comment]
Demo works well in IE7
http://fronteed.com/iCheck/

I hope you don't use Zepto, since it doesn't support IE7
http://zeptojs.com/#browsers

**Comment by MrGeneric** [comment]
I never even thought to check your site in IE7 mode, silly.

I'm using jQuery.

Thanks for the quick reply, just knowing that this issue is with my setup should be enough. Cheers.

**Comment by wangtae** [comment]
It's inline-block problem in IE7.
So you should modify your css file like this.

.icheckbox_flat,
.iradio_flat {
    display: inline-block;
    _display: inline; 
    zoom:1; /_\* add this one */
    vertical-align: middle;
    margin: 0;
    padding: 0;
    width: 20px;
    height: 20px;
    background: url(flat.png) no-repeat;
    border: none;
    cursor: pointer;
}
