### ISSUE TITLE
<ins>-Tag is covering everything else on the page.

### ISSUE THREAD

**Issue by ghost** [drgullin/icheck#114]
On Chrome 32, the generated `<ins>`-Tag is positioned absolute, while it's parent div is not positioned relative. Therefore the `<ins>` is covering everything else on the page, since it's `element.style` is

``` CSS
position: absolute;
top: 0%;
left: 0%;
width: 100%;
height: 100%;
```

Setting the generated div to `position: relative;` does fix this problem.
I don't know if this applies to all skins, but at least it applies to the minimal theme.

**Comment by drgullin** [comment]
iCheck sets `position: relative;` using `css()` method.

This style has been overwritten by some selector if it doesn't work for you.
Check the appended css files.

`<ins>` tag is dropped in iCheck v2.x, you may try to use a newer version instead https://github.com/fronteed/iCheck/tree/2.x-beta
