### ISSUE TITLE
Plugin not defined when file lazy loaded

### ISSUE THREAD

**Issue by codewhisper** [drgullin/icheck#121]
I'm using iCheck with Drupal and if I try to load the iCheck lib with an Ajax call I get the error, that the funciton "_icheck" does not exists. 

The solve the issue, I simply moved the plugin definition "$.fn[_icheck] = function(options, fire) {}" above the binding "$(_doc).on".

Regards,

Jakob

**Comment by drgullin** [comment]
Please provide a test link, I'll try to fix that. 

Do you use 1.x or 2.x version? All the things should be tested using the 2.x version.

**Comment by codewhisper** [comment]
Hi,

I'm sorry but I'm not able to setup a test environment right now. (Simply do not have the time). I will try sonish.

Anyhow, I'm using the 2.x version.

Regards

**Comment by drgullin** [comment]
Thanks, fixed in https://github.com/fronteed/iCheck/commit/982905edf9388c7982f937e27d7c270a7bdf7a7a
