### ISSUE TITLE
ICheck not working properly on Windows Server 2012 Standard 

### ISSUE THREAD

**Issue by dennisdevetter** [drgullin/icheck#123]
Hi,

We found an issue using the iCheck library running on Windows Server 2012 Standard. with the following combination
Browser Mode: IE10
Document Mode: IE7 standard

The checkboxes are not rendered at all (but the behavior itself still works)
You can try it by browsing to the demo website http://fronteed.com/iCheck/

Since we are using the tool in production we are kinda stuck right now :/

Regards
Dennis

**Comment by drgullin** [comment]
Hello Dennis,

Try to use 2.x version instead https://github.com/fronteed/iCheck/tree/2.x-beta
Note that it has a bit different syntax.

**Comment by dennisdevetter** [comment]
I tried with the latest version 2.x beta and after editing the breaking changes in naming('iCheck' to 'icheck' and 'check' to 'checked', etc) 
I tried it again on different browser modes of IE and it gave a better result than my previous version (0.9)

rendering mode | browser mode | result
IE7 | IE7 | OK
IE10 comp. | IE7 | OK
IE10 | IE7 | NOT OK (checkboxes are rendered correctly but the click doesnt fire the events "ifChecked", etc)

I definatly need this latest configuration to work.
any ideas for a fix?

kind regards
Dennis

**Comment by drgullin** [comment]
This issue is fixed by the latest commit.

Thanks for the heads up.

**Comment by dennisdevetter** [comment]
Great. thanks for the fast reply.
Works perfect now.

**Comment by drgullin** [comment]
You're welcome.
