### ISSUE TITLE
Checkbox gets selected while hovering in IE11, document mode IE10

### ISSUE THREAD

**Issue by dennisdevetter** [drgullin/icheck#124]
With the latest source of v2.0,I got a strange behavior that the checkbox gets selected withouth clicking, but just by hovering over the element.

**Comment by drgullin** [comment]
Oops.
I'll fix it tomorrow.

You can temporally switch off the `tap` option to make it work as expected.

**Comment by drgullin** [comment]
Does it work now?

Please make sure you've a `tap` option set to `true`.

You can add this code before you include the iCheck:

```
<script>
window.icheck = {
  tap: true
};
</script>
```

**Comment by dennisdevetter** [comment]
Fixed.
the tap option is by default set to true, so i dont need it ..

works like expected now. i'll use the latest code of FEB02.

**Comment by drgullin** [comment]
Nice to hear, thanks.
