### ISSUE TITLE
Bug: 'aria' option isn't working when set to false.

### ISSUE THREAD

**Issue by wle8300** [drgullin/icheck#125]
To my understanding, using the option "aria: false" when initializing should remove the aria-attributes, however it is not working for me right now.

Everything else is working fine.

This is the initialization code I'm using:

```
$(document).ready(function(){
  $('input').iCheck({
    checkboxClass: 'icheckbox_square-blue',
    radioClass: 'iradio_square-blue',
    increaseArea: '50%', // optional
        aria: false
  });
});
```

This is the HTML markup:

```
<form>
  <input type="checkbox" name="iCheck" data-permachunk="http://soundcloud.com{{track.permachunk}}" class="exclude">
</form>
```

**Comment by drgullin** [comment]
Current issue is fixed by a latest commit.

Thanks @williamle8300.

**Comment by drgullin** [comment]
You may also try to use a next version https://github.com/fronteed/iCheck/tree/2.x-beta

It doesn't block the native events, so there's no need for the aria attributes.

**Comment by wle8300** [comment]
Thanks for the help, and making this great project, @fronteed!
