### ISSUE TITLE
Bug when clicking on checkbox on Chrome and Firefox

### ISSUE THREAD

**Issue by dennisdevetter** [drgullin/icheck#129]
Hi,

Since the latest fixes for IE7 with iCheck checkboxes we now have a related bug.
We have a scenario where we have an icheck checkbox inside a row element (div)
the row element has a click event.
when we check the checkbox in the row, the checkbox is checked, but the row click is also triggered.

Can we prevent bubbling of the checkbox click event ? or can you fix this for all browser versions?
(IE does not have this behavior).

Thx in advance.

**Comment by dennisdevetter** [comment]
Sorry, was to quick reporting a bug.. its a none issue :)

**Comment by drgullin** [comment]
You're welcome ;)
