### ISSUE TITLE
jQuery onclick events for check/radio boxes not being passed

### ISSUE THREAD

**Issue by ahmdsmir** [drgullin/icheck#132]
So if you have a code like this:

<pre>    jQuery(document).ready(function(){
        jQuery("#CheckboxID").click(function () {
            if (jQuery("#CheckboxID:checked").val()!=null) {
                jQuery("#subaccountfields").slideDown();
            } else {
                jQuery("#subaccountfields").slideUp();
            }

        });
    });</pre>

The click event is not passed when using iCheck. Is there a workaround for that? I'm using iCheck with an existing CMS which has several of these functions and it's rather impossible to change each and every one of them. So I was hoping for an existing solution.

**Comment by skyzer** [comment]
I have same issue and because of that the project is overdue. Other friend recommended uniformjs which does not have same problem
                        jQuery('body').on('click', '.calculator-1 .iradio_minimal-blue', function() {
                            console.log("clicked iradiominimal");
                            alert("clicked iradio div");
                        });

**Comment by drgullin** [comment]
Please read this https://github.com/fronteed/iCheck#january-23-2014-v20-release-candidate

You won't get this issue in newer version.

**Comment by skyzer** [comment]
Thanks for quick info. Because I am using angularjs, luckily this helped me
https://github.com/fronteed/iCheck/issues/62

**Comment by drgullin** [comment]
You're welcome.

Angular.js can also be used with the 2.x version, there're already few notes about the integration.

@skyzer 2.x version doesn't have these issues.
