### ISSUE TITLE
HTML Select Support

### ISSUE THREAD

**Issue by maxbailey** [drgullin/icheck#136]
Would this plugin ever extend to support the select tag?

**Comment by drgullin** [comment]
Hello @maxbailey 

What do you mean?

**Comment by maxbailey** [comment]
Sorry about that, markdown removed part of what I said. Will this plugin be extended to work with native HTML dropdowns?

http://jsfiddle.net/WyQPM/

**Comment by drgullin** [comment]
Nope, sorry.

iCheck is only for a checkboxes and radio buttons.
Another plugin will be released soon for a dropdowns customization.

**Comment by maxbailey** [comment]
Awesome, thanks.
