### ISSUE TITLE
Not mobile friendly?

### ISSUE THREAD

**Issue by rickjedi** [drgullin/icheck#138]
I just installed iCheck on my site and it works on the desktop, but the buttons dont even show up on my Mobile (Samsung Galaxy S3 mini).

Here's the URL.

http://md1network.com/user/register/

**Comment by drgullin** [comment]
http://md1network.com/img/blue@2x.png

```
Not Found
The requested document was not found on this server.
```

**Comment by rickjedi** [comment]
Thanks for the reply. That was the issue.
