### ISSUE TITLE
Opacity problem

### ISSUE THREAD

**Issue by xavadu** [drgullin/icheck#139]
Hello,
i read there at i feel free to submit a issue if i found a problem, here i am.. 

any idea why it is not working?
http://jsfiddle.net/buRq7/8/

it should, iCheck wrap the input field but opacity keep in zero and anyway if i modify it by the console, doesn't work

Thanks

**Comment by MrGeneric** [comment]
Hey, hope this helps you. :)
http://jsfiddle.net/SUTMf/

**Comment by xavadu** [comment]
thanks @MrGeneric , the external resource of the library was not working (i changed it) and it's work, i realize that the problem was don't have the css file loaded 

http://jsfiddle.net/SUTMf/1/
