### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by baurez** [drgullin/icheck#14]
Hi,

I have to check in javascript my CHECKBOX...

So i start to do this $('#ID').click(); to perform this...

But it doesn't work...

I see in the plugin that : 

```
if (type == 'click') {
                            return false;
```

so my event is never fired... and nothing changed...

Why the plugin don't work like this:
- I click my ICHECK checkbox
- this fire the click event of my checkbox
- this click event of the checkbox fire the update of my icheck

Like this... if an onclick event is attached to my original checkbox, it will continue to work.

What do you think ?

thanks

**Comment by drgullin** [comment]
This scheme was replaced in version 0.8, because of the bugs related to customized inputs inside labels and different way of handling key events in some browsers.

`return false` also prevents an infinite loops in some cases.

Since iCheck is used for customization, I hope we don't need to fire direct clicks on an inputs. 

I would like to add a `toggle` method instead, which would work like an ordinary click:

``` js
$('input').iCheck('toggle');

:checkbox checked => uncheck
:checkbox unchecked => check
:radio checked => do nothing
:radio unchecked => check current, uncheck others
```

**Comment by baurez** [comment]
Yes. But the goal of plugin like icheck is to make the input more
beautiful. And it will be easy to add un any project. And all the normal
évent attached to the original input must be preserved.

For example, in ASP.net we can easyly make a submit of thé form when thé
checkbox state change... This possibility is triggered by the click
évent... With icheck this never happened.

In the same way, original event on chzckbox could be executed by thé icheck
no ?

**Comment by drgullin** [comment]
iCheck doesn't use click event to make changes, it works directly with input's state instead.

I hope ASP.NET can handle `ifChanged` callback. It has almost the same effect, as a click event.

This code: 

``` js
$('input').click(function(){
  // submit
});
```

Should be replaced with:

``` js
$('input').on('ifChanged', function(){
  // submit
});
```

**Comment by drgullin** [comment]
I've added a `toggle` method. It can be used instead of the click event. To handle clicks, use `ifClicked` callback.
https://github.com/fronteed/iCheck/commit/f5da1d7cfc4d7fecfe7b55c8ebcfb56222dbfd8b

**Comment by drgullin** [comment]
Next version will support click handler on inputs.

**Comment by desduvauchelle** [comment]
Not sure if it's linked. But how come when I click a checkbox it doesn't toggle the actual checkbox state (ie from checked to unchecked) when I look at the source code?

Here is my setup: 

```
$('input').iCheck({
    checkboxClass: 'icheckbox_square-blue',
    radioClass: 'iradio_square-blue',
    increaseArea: '20%' // optional
});

$('input').on('ifChanged', function(event){
    alert(123);
});
```

But nothing happens.

**Comment by ambasador** [comment]
Hi this is working for me fine

$('input').iCheck({
    checkboxClass: 'icheckbox_square-blue',
    radioClass: 'iradio_square-blue',
    increaseArea: '20%' // optional
});
$('input').iCheck('update');
$('input ').on('ifClicked ', function(event) {
    if ($('input').prop('checked')) {
        alert('1');
    } else {
        alert('2');
});

**Comment by desduvauchelle** [comment]
Thanks for the super fast feedback. 

![screen shot 2013-08-15 at 19 37 02](https://f.cloud.github.com/assets/1172911/970202/007a5d7a-05d2-11e3-9524-b8d33df5ce3d.png)

I just added your code to my site...and it doesn't work. The checkboxes are nice and sexy, but no alerts on click...Might be collision with a script...hummm.

**Comment by neylith** [comment]
Hi, @desduvauchelle  I have your problem with iCheck, 

$('input').on('ifChanged', function(event){
    alert(123);
});

No work. How did you fix it?

Thanks
