### ISSUE TITLE
Retina images not working

### ISSUE THREAD

**Issue by ghost** [drgullin/icheck#140]
Hello. I have macbook pro 13' and retina display images are not wokring
I i change media query to this:

@media 
(-webkit-min-device-pixel-ratio: 2), 
(min-resolution: 192dpi) { 
    .icheckbox_flat-red,
    .iradio_flat-red {
        background-image: url(red@2x.png);
        -webkit-background-size: 176px 22px;
        background-size: 176px 22px;
    }
}

Then images appear as they should.

**Comment by drgullin** [comment]
HiDPI media rules should be revised, current ones are a bit outdated.

Does this one work for you?

```
@media (-o-min-device-pixel-ratio: 5/4), (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi) {
   // styles
}
```

**Comment by ghost** [comment]
@fronteed Yes, your new posted settings works as well as mine.
