### ISSUE TITLE
ipad ios7 issue

### ISSUE THREAD

**Issue by kamie** [drgullin/icheck#142]
On ipad ios7 only (ios6 works just fine), the checkbox are not working properly when they were not visible on load. The class "checked" is being added but visually the checkbox is not checked. Looking closer it looks like there is an image of the "checked" checkbox behind one that isnt checked.

I have looked on http://fronteed.com/iCheck/ and i have seen the same issue. Well I cannot see the image behind because the image you are using is not bigger then the not checked version, but if you keep clicking the checkboxes you will see that sometime they check, sometime they dont.

**Comment by drgullin** [comment]
Use 2.x beta, 1.x version is quite outdated.

**Comment by kamie** [comment]
That is what I am using. I use fastclick and the other version was not compatible.

**Comment by drgullin** [comment]
Thanks for submitting this. Android 2 had a same issue (when `tap` option is active).
This happens because of the events delays specifity.

It should work better now, check out a 2.x version.
Tested on iOS 7.0.6.
I've also tested styling of the invisible inputs - works well.

**Comment by kamie** [comment]
I still have the bug on ipad IOS version 7.0.6. The tap is set to true.
The funny thing is, if I move the page just a little, then the checkboxes appear (no interaction other than just scrolling the page).

**Comment by drgullin** [comment]
Provide a demo please.

**Comment by kamie** [comment]
I cant reproduce it in a demo. The rest of the problem must be due to my complexe layout, probably on my end. You can put that to fix, thank you :)

**Comment by andreas-stricker** [comment]
i think i have the same problem. where can i download version 2.x?

**Comment by drgullin** [comment]
https://github.com/fronteed/iCheck/tree/2.x

**Comment by andreas-stricker** [comment]
oh, i have more problems on desktop firefox and safari with v 2.x
is there a better possibility to change the bug on ipad in v 1.0.2 ?

how to disable tap option? does it work then on android and ios?
