### ISSUE TITLE
Multiselect with shift key

### ISSUE THREAD

**Issue by bart** [drgullin/icheck#152]
Is it possible to detect, if a checkbox has been shift-clicked? I want to implement a shift-select feature, so I need to get this information.

```
$('.checkbox input').on('ifClicked', function(event){
    alert(event.shiftKey);
});
```

This returns undefined :(

**Comment by drgullin** [comment]
Nope.

You can use `keydown` event to detect specific key codes:

```
$('input').on('keydown', function(event) {
  alert(event.keyCode);
});
```

**Comment by stkrzysiak** [comment]
Is this maybe on the roadmap?
