### ISSUE TITLE
Uncaught TypeError: Cannot set property 'keydown' of undefined in iCheck v2.0.0 RC1

### ISSUE THREAD

**Issue by iliaross** [drgullin/icheck#160]
If you get onto iCheck ( used with radio) from some other input field using tab key, then you have an error in console. It continues to work properly and throws no more errors afterwards.

If you comment out the following line:

```
hashes[key].keydown = hashes[lastKey].keydown = false;
```

Then there is no problem at all.

Why is this really happening?

**Comment by patstuart** [comment]
I also encountered this bug on key press with JQuery 1.7.2 and JQueryUI 1.10.4.

It occurs because lastKey is undefined.

It occurs in the newest releases of Opera, Chrome, Firefox, and IE.

It does not occur in v1.0.2.

**Comment by drgullin** [comment]
Thanks @qooob and @patstuart.
