### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by GittiHab** [drgullin/icheck#163]
##### Just a quick question:

How do I resize iCheck checkboxes? If I change the width and hight in the css, nothing changes.

```
.icheckbox_square-grey,
.iradio_square-grey {
    width: 22px;
    height: 22px;
}
```

to

```
.icheckbox_square-grey,
.iradio_square-grey {
    width: 26px;
    height: 26px;
}
```

**Comment by drgullin** [comment]
You can set your own CSS classes and use them instead.
