### ISSUE TITLE
Get current state

### ISSUE THREAD

**Issue by it-can** [drgullin/icheck#175]
Hi,

Is there a way to get the current state of an iCheck checkbox/radio?

I have a submit button but that checks a couple of checkboxes before posting the form... It seems that _$('.terms').prop('checked')_ is not working...

**Comment by robertdodd** [comment]
Calling `$('.my-checkbox').prop('checked')` returns the correct value for me, but it only works for checkboxes and also depends on your jquery version.

**jQuery 1.6+**

```
$('#isAgeSelected').prop('checked')
```

**jQuery 1.5 and below**

```
$('#isAgeSelected').attr('checked')
```

All credit to: http://stackoverflow.com/a/426276/443427

Does that help?

**Comment by it-can** [comment]
thanks!
