### ISSUE TITLE
hashes[...] is null or not an object

### ISSUE THREAD

**Issue by dennisdevetter** [drgullin/icheck#180]
There is an issue on a windows 2008 server running IE8.
When opening a page which has checkboxes wired to icheck, a javascript error pops up.
![javascript_error](https://cloud.githubusercontent.com/assets/3809698/3067024/c78838f0-e27d-11e3-8270-62467a825115.png)

Are you familiar with this error?
We can not always reproduce this error though.

**Comment by drgullin** [comment]
Provide a test case, please.

**Comment by patstuart** [comment]
This is a duplicate to https://github.com/fronteed/iCheck/issues/160.
