### ISSUE TITLE
check all / uncheck all problem

### ISSUE THREAD

**Issue by Mathias89** [drgullin/icheck#182]
I have 100 checkboxes and one for un/check them all.
'''
$(document).on('ifToggled', '.check-all', function() {
  if (this.checked) {
    $('.to-change').icheck('checked');
  } else {
    $('.to-change').icheck('unchecked');
  }
});
'''
The problem is that I don't want that the event ifToggled is fired for the to change inputs.
How can this prevented? I just want to update the view and not the behaviour that the 100 checkboxes were checked.

Here is an image:
![image](https://cloud.githubusercontent.com/assets/7727120/3110407/1fad2b46-e6a5-11e3-912f-acc6ee72001e.jpg)

How it should work: first checkbox un/checks all others.
Each checkbox enumerates the info where a checkbox is checked.

But if i use the above code the function for the enumeration is called by each checkbox and I have to wait a while...
Thanks in advance

**Comment by drgullin** [comment]
This question has already been asked.
