### ISSUE TITLE
Dynamically change radio button class

### ISSUE THREAD

**Issue by jjokocha** [drgullin/icheck#183]
I have been trying unsuccessfully to dynamically change the class and set a radio button dynamically. I am using icheck v2.0 and jquery 1.11.1. I start out with the following:

```
$("#input").icheck({
  radioClass: 'iradio_flat-blue'
 });
```

I am doing the following to change the class to iradio_flat-green when the user clicks on the right answer and iradio_flat-red when he clicks on the wrong answer.

```
if ( right_answer ) {
   $("#input").icheck({
           radioClass: 'iradio_flat-green'
    });
     $("#input").icheck('check');
     $("#input").icheck('update');
     $("#input").trigger('click');
}
else {
     $("#input").icheck({
            radioClass: 'iradio_flat-red'
     });
     $("#input").icheck('check');
     $("#input").icheck('update');
     $("#input").trigger('click');
}
```

For some reason, when I call the check method, it does not set the radio button, hence the need to trigger click. I get the following error in Firefox: TypeError: hashes[key].callbacks is undefined and in IE: Unable to get property 'ifChanged' of undefined or null reference and refers to the following code snippet in icheck.js:

```
if (typeof hashes[key].callbacks[name] == 'function') {
            hashes[key].callbacks[name](node, hashes[key]);
          }
```

Any insight / help is greatly appreciated,

Thanks

**Comment by drgullin** [comment]
Fixed by https://github.com/fronteed/iCheck/commit/ed7424e7562d9ced37265a75ff9eacb4260c0367
