### ISSUE TITLE
Don't unchecked when form reset...

### ISSUE THREAD

**Issue by lotestudio** [drgullin/icheck#187]
It's not a big deal, but when use something like that:
<code>document.getElementById("some_form").reset();</code>

The input checkbox is uncheked, but skin stay checked.
Must use something like that:
<code>
$('#somecheckbox').iCheck('uncheck');
document.getElementById("some_form").reset();
</code>
First uncheck, after that reset...and it's works, but not so elegant.

**Comment by drgullin** [comment]
Duplicate of https://github.com/fronteed/iCheck/issues/146
