### ISSUE TITLE
mouse down state

### ISSUE THREAD

**Issue by szepeviktor** [drgullin/icheck#189]
E.g. Firefox has a "mouse button down" state of unselected - and even selected - radio buttons, checkboxes.
Do you plan to support it?

**Comment by drgullin** [comment]
Your question is about the active state. Use `activeClass` option.

**Comment by szepeviktor** [comment]
Do you plan to add CSS to `activeClass` in _stock_ iCheck?

**Comment by drgullin** [comment]
`activeClass` is available in stock of 1.x version.

It's not added by default in 2.x, because `hoverClass` and `activeClass` are almost similar on touch devices.
