### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by ckizer** [drgullin/icheck#19]
Installation doesn't seem to be covered anywhere. From the sample docs it's not clear if I really need to include all 5 of your separate javascript files in the header.

What's the best way to quickly get flat style in another project i have without trying to change all my paths and such around (rails project)

It's a bit confusing…

**Comment by drgullin** [comment]
All you need to include (by default) is jQuery itself (or Zepto) and `jquery.icheck.js` (or `zepto.icheck.js`). In this case, you're free to customize inputs the way you need.

If you want to use preferred skin instead, you should check **Usage** tab, which is available on the right side of each skin.

**Comment by ckizer** [comment]
I did that, but it fails to work.

```
[Error] ReferenceError: Can't find variable: Zepto (zepto.icheck.min.js, line 10)
```

**Comment by drgullin** [comment]
Seems you're trying to use `zepto.icheck.min.js` with jQuery. Since it's a separate version for a Zepto library, it won't work with jQuery.

For jQuery you should use `jquery.icheck.min.js`.

**Comment by ckizer** [comment]
I didn't choose anything, I just downloaded your package and dragged the js files from demo html into my project. I had no idea you weren't using jquery since you said jquery is required.

Sorry, I understand what's going on now, you wrote it for both, and I dragged the wrong one from the repo into my project. Can we add a really clear note about this in the readme. I'm usually pretty sharp about this sort of thing, but got really frustrated quickly :package:

**Comment by ckizer** [comment]
It still doesn't work, now all my pages with forms load completely blank… this is so strange…

**Comment by drgullin** [comment]
Well, there's a note:

> By default, iCheck doesn't provide any CSS styles for wrapper divs (if you don't use skins).

That's why your inputs are blank, you have to add some CSS to style them, or you may use skins instead. 

Installation is a bit different for skins, you should check **Usage** tab on the right side of the preferred skin.
