### ISSUE TITLE
unrecognized expression: label[for=] with jquery 1.11.2 and 2.1.1

### ISSUE THREAD

**Issue by lostsnow** [drgullin/icheck#190]
When I upgrade jquery to 1.11.2, an error occurred:

> Error: Syntax error, unrecognized expression: label[for=]

I also test on jquery 2.1.1, the probelm is same.

1.9.1, 1.10.2 and 2.0.3 is ok.

My browser is Firefox 30.

**Comment by dylanbromby** [comment]
Are you trying to get or set the value? If you're trying to get it, try this:

``` javascript
$("label[for='{whatever}']").text();
```

Replace {whatever} with ... well, whatever.

**Comment by lostsnow** [comment]
oh sorry, I use the old version(0.7). the new version does not have this problem.
