### ISSUE TITLE
Inherit title

### ISSUE THREAD

**Issue by thekrotek** [drgullin/icheck#191]
Not sure, if it's an issue or feature request, but input title is not inherited right now. Would be nice to have it copied to wrapping div to preserve hints.

**Comment by thekrotek** [comment]
Actually, found the solution myself. Just needs 2 lines of code to be added.

Find: id = node.id,
Add below: title = node.title,

Find: !!settings.inheritID && id && parent.attr('id', _iCheck + '-' + id);
Add below: !!settings.inheritTitle && title && parent.attr('title', title);

Usage: add a new inheritTitle option, when inialized:

inheritTitle: true

**Comment by drgullin** [comment]
Use 2.x version.

There's an option for this:

```
$('input').icheck({
  inherit: 'title class'
});
```
