### ISSUE TITLE
method check() vs. update()

### ISSUE THREAD

**Issue by logemann** [drgullin/icheck#193]
Hi,

i have a strange behavior. I want to preselect a checkbox based on db data from REST call.

if i do:

```
$('#active').iCheck('check');
```

nothing happens and my checkbox is still unchecked. But when i do:

```
$('#active').attr("checked", active).iCheck("update");
```

everything is fine. But this is somehow strange to me. Can anyone point me to the right direction?

thanks

**Comment by drgullin** [comment]
No demo - no honey, sorry.
