### ISSUE TITLE
iCheck v2.x problem with jumping page on click?

### ISSUE THREAD

**Issue by Daijobou** [drgullin/icheck#195]
Hello,

I click on checkbox and the page jump down. Have anyone this problem too? Its not on all pages with iCheck, but its only happen with iCheck is active.

EDIT: Problem is in IE10, FF, Chrome but in each browser with different scroll-height.

EDIT:
Founded. The problem was (my) css style "bottom"

```
input[type=checkbox], input[type=radio] {
    bottom:2px;
}
```

after delete this line, all working fine. :)

or better, add position:relative to

```
.icheckbox, .iradio {
position:relative;
```

So I must not change my original css code.

**Comment by khanfx** [comment]
Just reporting that I experienced this too when using iCheck in a Bootstrap popup with scrolling, and confirming that Daijobou's fix worked. Make sure you reference the right class for your theme.

.icheckbox_square-red { position: relative; }
