### ISSUE TITLE
Is this project still in development?

### ISSUE THREAD

**Issue by Daijobou** [drgullin/icheck#199]
I like this component, but is this still in development? Last update is 5 months old. I plan a little project with nice checkboxes, but is iCheck the right choice?

**Comment by drgullin** [comment]
iCheck v2 update coming soon.

**Comment by Daijobou** [comment]
Glad to hear. I like this style checkbox. Thanks for your work. :)

**Comment by bramstroker** [comment]
Any update on this? We really want to use v2 in our project, but we need a somewhat stable version.
The current beta version has some minor issues. I'm also a little concerned about the time since last commit. Thanks for your efforts.

**Comment by drgullin** [comment]
I'm sorry guys, too much work now. I'll be back soon with a v2 issues fix.

You're free to provide a workaround for an existing issues.

**Comment by Daijobou** [comment]
Better later as never again. I hope you found a little time for this great plugin. Thanks for your work. :)

**Comment by drgullin** [comment]
iCheck will get an update by the end of the month.
