### ISSUE TITLE
Highlight label if checkbox/radio is checked

### ISSUE THREAD

**Issue by SiteSplat** [drgullin/icheck#201]
Is this part of the options? I didn't see any examples..

**Comment by Daijobou** [comment]
Only standard jQuery is here needed:

$("label[for='your-id']")

```
$('input[type="checkbox"]').click(function() {
    $("label[for='"+$(this).attr("id")+"']").css('color', 'red');
});
```

**Comment by drgullin** [comment]
This option is available in v2.

Use `mirror` option.
