### ISSUE TITLE
skins source

### ISSUE THREAD

**Issue by quasiperfect** [drgullin/icheck#21]
hi

i tried to modify the png to fit my theme but no luck can you post the source of the png file ?

**Comment by daenuprobst** [comment]
You are aware that virtually every image editor from Windows Paint to Photoshop can edit png files?

**Comment by quasiperfect** [comment]
i was thinking you used corel or any other vector (would be very easy for everyone to color replace and create themes fast) editor so i asked for the source
yes every image editor can edit png files. you have transparence there so is not just color replace
thanks for you work and sorry i wasn't more explicit in my request
