### ISSUE TITLE
Don't stop propagation or return false on events

### ISSUE THREAD

**Issue by timocouckuyt** [drgullin/icheck#211]
I should point out that, when returning false or stopping propagation on events, these events don't get pushed to other jquery plugins binding to these events. This can lead to some irritating situations when validating forms. For example, other jquery code might not be able to show/hide form fields, when checkboxes or radio buttons are clicked.

I've commented out the return false / event.stopPropagation() lines to avoid this.

**Comment by drgullin** [comment]
v2 doesn't block native events.
