### ISSUE TITLE
Generic node event

### ISSUE THREAD

**Issue by luka8088** [drgullin/icheck#217]
I am wondering why iCheck triggers only iCheck specific events. Shouldn't it also trigger generic events? 

For example, triggering 'change' along with 'ifChanged' on https://github.com/fronteed/iCheck/blob/d3b53e6d36/icheck.js#L311 would allow other seamless replacement of default html checkboxes with iCheck ones.

What do you think?

**Comment by drgullin** [comment]
iCheck 1.x version blocks native events, while 2.x doesn't block any existing events.
