### ISSUE TITLE
Checkbox CSS not applied with Angular JS

### ISSUE THREAD

**Issue by romsjain** [drgullin/icheck#218]
HI,
I have created a div with checkbox input and also JQuery code to apply CSS.
This simple approach is working. But if I make this approach with Angulas JS then it doesn't.

Below is the code which is working fine.

```
<div class="layout clear">
    <div class="skin skin-minimal">
        <input type="checkbox" id="minimal-checkbox-1">
    </div>
</div>
```

But this code is not applying CSS to my checkbox.

```
<div class="col-xs-12">
    <div class="col-xs-3" ng-repeat="productType in productTypes | groupBy:['compressorTypeDesc']">
        <div class="layout clear">
            <div class="skin skin-minimal">
                <input type="checkbox" id="minimal-checkbox-1">{{xyz}}
            </div>
        </div>
    </div>
</div>
```

Can you suggest me, where am I making mistake??

**Comment by mrhammadasif** [comment]
@romsjain Please can you guide me, How have you solved this issue ?
