### ISSUE TITLE
Crashes safari in Yosemite with voiceover on

### ISSUE THREAD

**Issue by tbredin** [drgullin/icheck#221]
Title says it all

**Comment by sawks** [comment]
+1

**Comment by Daijobou** [comment]
version 1 or 2 or both?

**Comment by sawks** [comment]
1.0.2 - will try the 2.x branch

**Comment by drgullin** [comment]
I'll take a look.

**Comment by tbredin** [comment]
Can confirm the issue doesn't occur on the 2.x branch! 

But I noticed 2.x doesn't have an aria option yet... just wondering - is this planned or has it been removed for some reason?

**Comment by drgullin** [comment]
It's just not implemented yet.

**Comment by drgullin** [comment]
http://fronteed.com/iCheck/ doesn't crash Safari with Voiceover on.

You've likely too many inputs on your page.
