### ISSUE TITLE
iCheck does not update element state when it be check by a jquery trigger

### ISSUE THREAD

**Issue by quyenbui** [drgullin/icheck#226]
There are link with click event, I click that link all specify elements will be change state to checked.
If i no use iCheck it working. But use iCheck do not work.
Please fix it thanks

**Comment by quyenbui** [comment]
http://jsfiddle.net/40sowk8x/1

**Comment by drgullin** [comment]
You should use `update` event.

http://jsfiddle.net/40sowk8x/2/

**Comment by quyenbui** [comment]
Thanks for your help

**Comment by drgullin** [comment]
You're welcome!
