### ISSUE TITLE
Infinit loop of callback calling when changing radio state more than once

### ISSUE THREAD

**Issue by mazoo** [drgullin/icheck#227]
I am using 2.0 RC1 in a Drupal 7. Using radios which trigger an ajax call. When switching the radios checked state from one to the other radio, the very first time, it works fine. But switching a second time, an infinit loop of automatic switching starts. Any idea what this could be?

**Comment by drgullin** [comment]
Please provide an example on jsfiddle.

**Comment by mazoo** [comment]
Hardly possible to demonstrate the Drupal aspects on jsfiddle. I should probably deploy it on a public site? Motivation was to use 2.0 because 1.0.2 does fire only the first change event of radios/checkboxes (even within on('ifChecked'...)). I suspect some problems with the drupal js/ajax framework in both cases.

**Comment by drgullin** [comment]
Sure, please provide the code you use and a link.

**Comment by mazoo** [comment]
Hey, thanks a  lot!
I use your icheck.js 2.0 RC1, the newest one from yesterday :)
The link: https://removed/?collapsible=1&step=3
Do the following, to reproduce the infinite loop:
1. You see the Radios "Nein" and "Ja" -> click on "Ja" (It triggers an ajax call, that works fine, the checked state does not)
2. Now click on the "Nein" radio button, which still seems checked, but just click it once more (now, the infinite loop of calling the ajax-request starts...)

We're loading your resource (ickeck-2.0.js) and are setting the data-\* attributes on the respective radios
'#attributes' => array(
      'class' => array('icheck'),
      'data-radioClass' => 'iradio_minimal-konto'
)
That's it. No unnecessary init call and stuff like that :)

**Comment by drgullin** [comment]
Something likely wrong in your code, since it sends an ajax requests, when I click on a checked radio button. It shouldn't do that, I guess.

Where's the code you use to send ajax requests?

**Comment by mazoo** [comment]
Thanks for checking.
The ajax request is triggered and managed on change by Drupal Form API. With icheck 1.0.X, in the same context, the issue is different. Only the first change event (of radios/checkboxes) gets fired.

**Comment by drgullin** [comment]
Something blocks native input events, since iCheck can't handle the input state changes.

Try to send the ajax requests on ifChecked/ifUnchecked callbacks.

**Comment by mazoo** [comment]
Generally or only for icheck 1.0?

**Comment by drgullin** [comment]
Generally.
iCheck v2 doesn't block native events, but it can't handle the updates, since something blocks them instead.
Btw, does iCheck work on that page without using the ajax requests transmitter?

**Comment by mazoo** [comment]
Yes, you'll find a check box example here /?collapsible=1&step=1 (if you still know the host) :)

**Comment by drgullin** [comment]
It doesn't work for me there.
