### ISSUE TITLE
icheck with jquery 1.11.1 js

### ISSUE THREAD

**Issue by dadatest** [drgullin/icheck#229]
Hi, 
Can I use your code when also using the jquery 1.11.1.js? It doesn't seem working when I included the jquery 1.11.1.js, but it works with the styles after I removed the jquery.1.11.1.js. 

Any suggestions? We will have to use jquery.1.11.1.js on our template. 

Thanks Linda

**Comment by drgullin** [comment]
Both versions work well with jQuery v2.1.1 and v1.11.
