### ISSUE TITLE
Serialize Input[checkbox and radio] issue with jQuery

### ISSUE THREAD

**Issue by timothymarois** [drgullin/icheck#23]
I've noticed jQuery `$('xxx').serialize()` can not read the input of checkbox/radio when I'm submitting through `$.post()` (which shouldn't make a difference).

I have tested running iCheck and disabling iCheck. `serialize()` is unable to read those variables. However, it works perfectly fine on other input types.

I've worked to try to figure out what is causing the issue. but it seems to be an issue when you do multiple forms on the same page with the same name inputs, thats what I've been able to reproduce. 

```
<form id="form1"><input type="radio" name="test"></form>
<form id="form2"><input type="radio" name="test"></form>
```

(that is where it seems to have an issue sending the data to serialize.) I have removed iCheck and the setup worked perfectly. If you do one form, it worked fine.

**Comment by abrambailey** [comment]
Is this working now? I am having the same issue with the latest version.

**Comment by marvoh** [comment]
+1
