### ISSUE TITLE
Trigger events on original input

### ISSUE THREAD

**Issue by georgir** [drgullin/icheck#238]
This needs to work as a drop-in replacement of default inputs, without changing existing scripts that bind change or click events. It must trigger the default event handlers, and possibly get rid of the crazy custom events.

**Comment by drgullin** [comment]
It's available in 2.x branch, just use it.

**Comment by rdetert** [comment]
Using 2.x and it works for the click event but it doesn't seem to bind to the `change` event. That is, if I programmatically check a checkbox, the skin display doesn't change with it.
