### ISSUE TITLE
Implement "readonly" state

### ISSUE THREAD

**Issue by billmn** [drgullin/icheck#25]
Now iCheck support the "disabled" state but not the "readonly" state ... and I haven't found a workaround.

This can be a feature request ? :)

**Comment by drgullin** [comment]
http://stackoverflow.com/questions/155291/can-html-checkboxes-be-set-to-readonly/
http://stackoverflow.com/questions/1953017/why-cant-radio-buttons-be-readonly

**Comment by billmn** [comment]
oh ok ... sorry for that

**Comment by Hazarapet** [comment]
It's not working at all.
