### ISSUE TITLE
Having troubles referencing iCheck

### ISSUE THREAD

**Issue by Charleezy** [drgullin/icheck#272]
```
<script src="@Url.Content("~/scripts/icheck.js")" type="text/javascript"></script>
$(document).ready(function () {
              $('input').iCheck({
                  checkboxClass: 'icheckbox_minimal',
                  radioClass: 'iradio_minimal',
                  increaseArea: '20%' // optional
              });
```

Visual studio has a reference to iCheck but for some reason on Chrome, I can't find a reference to iCheck and get `"Uncaught TypeError: $(...).iCheck is not a function"`

I'm not sure I can get this to reproduce as the problem doesn't appear on a different project.
But how do I go about debugging this?

**Comment by drgullin** [comment]
Give me a link please.

**Comment by Charleezy** [comment]
Can't get the fiddle to work. Sorry. I'll just remove iCheck for now. Thanks.

**Comment by Charleezy** [comment]
It seems to have been an issue with how I was referencing the script and not with iCheck.

I changed from referencing in a layout page to the view page and iCheck started working. Weird.
