### ISSUE TITLE
How to get value from iCheck element

### ISSUE THREAD

**Issue by titopandub** [drgullin/icheck#276]
Hi, I want to ask, how to get value from iCheck element?

I used this code, but the value is always 1.

```
  $("#selector").val();
```

**Comment by irfanifirdausy** [comment]
$('#selector').on('ifChanged',function(e){
    e.preventDefault();
    var status_val  = $(this).val();
   alert (status_val);
)}

you can use $('#selector').on('ifChanged ifClicked',function(e){ ...
depending on your case :)

**Comment by titopandub** [comment]
But, this method only show value if it's checked, which is 1. When checkbox become uncheck, then the value is nothing (not even printed in console.log).

I have fixed this by using inline style to element that I wish to hide from backend, then it will be showed or hide based on ifChecked or ifUnchecked.

Thank you for your support.
