### ISSUE TITLE
Trouble with callbacks

### ISSUE THREAD

**Issue by CharlyPoppins** [drgullin/icheck#286]
Hi,
trying ti use callbacks but it didn't work

``` javascript
$('.tree input[type="checkbox"]:not(".switch")').iCheck({
        checkboxClass: 'icheckbox_flat-purple',
        increaseArea: '-30%'
    }).on('ifToggled', function(event){
        console.log("toggled");
        $(this).parent().parent().addClass("tree-selected");
    }).on('ifChecked', function(event){
        console.log("add selected");
        $(this).parent().parent().addClass("tree-selected");
    }).on('ifUnchecked', function(event){
        console.log("remove selected");
        $(this).parent().parent().removeClass("tree-selected");
    });
```

``` javascript
var Radios = $('.tree input[type="radio"]:not(".switch")');
    $(Radios).iCheck({
        radioClass: 'iradio_flat-purple',
        increaseArea: '-30%'
    });
    $(Radios).on('ifToggled', function(event){
        console.log("toggled");
        $(this).parent().parent().addClass("tree-selected");
    });
    $(Radios).on('ifChecked', function(event){
        console.log("add selected");
        $(this).parent().parent().addClass("tree-selected");
    });
    $(Radios).on('ifUnchecked', function(event){
        console.log("remove selected");
        $(this).parent().parent().removeClass("tree-selected");
    });
```

What am I missing ?

**Comment by vanydiah** [comment]
Hi, i have a similiar problem

<pre>
$(document).ready(function(){
    $('.feed').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
            increaseArea: '20%' // optional
     });
});
</pre>

i want to give 'active' state on the label if it's radio button checked,
i use these codes below but none of them are working...
1.

<pre>
$('.feed').on('ifChecked', function(){
    $('.iradio_square-green.checked').siblings('label').addClass('active');
});
</pre>

2.

<pre>
$('.feed').on('ifChecked', function(){
    if ($(this).parent('.iradio_square-green').hasClass('checked')){
        $(this).parent('.iradio_square-green').siblings('.label').addClass('active');
        $('.content-item .feed_backform .itemlabel').not($(this).parent('.iradio_square-green').siblings(' label')).removeClass('active');  
    }
});
</pre>

**Comment by CharlyPoppins** [comment]
Still haven't found yet...

**Comment by andreyvolokitin** [comment]
You should bind events before iCheck initialization

**Comment by CharlyPoppins** [comment]
I use ifChanged on both radio and checkbox, and trigger the change event of the input, then I bind .change on radios that find a checkbox, check the input and update the iCheck object.

```
$('.tree input').on('ifChanged', function (event) { $(event.target).trigger('change'); });
$('.tree input[type="radio"]').change(function() {
        // find an input
        $(input).attr('checked', this.checked);
        $(input).iCheck('update');
}
```
