### ISSUE TITLE
The plugin does not work on Android devices

### ISSUE THREAD

**Issue by frontendr** [drgullin/icheck#31]
The checkboxes and radio inputs only receive focus when tapped. When I tap multiple times they 'sometimes' check.

**Comment by sanderlissenburg** [comment]
It's only in the Chrome browser for Android. The div is getting focused(becomes blue) but no event is triggered. Sometimes after some touching the event is fired.

**Comment by sanderlissenburg** [comment]
Some more information. I use android 4.2. Also your own demo page is not working.

**Comment by drgullin** [comment]
Some things changed after previous version.

I'll test iCheck for the mobile compatibility again and release a stable version asap (0.9).
