### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by boughtonp** [drgullin/icheck#318]
There have been no commits or issue comments since May 2015 for either 1.x or 2.x branches.

Is v2 still under development?
Is there another repo/fork to use?

**Comment by jackfischer** [comment]
+1. Would be helpful if we had news on 2.0

**Comment by Zmove** [comment]
The project seems abandonned. Even the 2.0 that is on RC1 didn't receive any update since years.... looking for a maintained alternative.

**Comment by giovkanata** [comment]
I don't know if there is someone (one or more) with the necessary knowledge (and time availability) to be able to become the maintainer of this project, but this is the real problem of the open source and this is also the first reason for which I know that before starting to use any library, project, etc... in some important project, I have to think about whether I will be able to maintain it by myself in the case it will be abandoned.

**Comment by Chrysweel** [comment]
ping @fronteed @damirfoy

**Comment by piglei** [comment]
@Zmove Any recommendations for icheck alternative?

**Comment by fractefactos** [comment]
Bump!

**Comment by iamsolarplexus** [comment]
The Uniform.js library is maintained and looks pretty solid.  And the skins icheck uses are free to use, so you just need to create a new sprite to pop them into Uniform.

Maybe someday icheck will return from the ashes.  I hope so.  Until then, Uniform looks good!

**Comment by cyphix333** [comment]
I've been using this for years but I guess I should stop using it as it's definitely abandoned lol; bit of a shame.

**Comment by drgullin** [comment]
@boughtonp library is maintained now. Thanks for the patience.
