### ISSUE TITLE
Add event delegation support

### ISSUE THREAD

**Issue by shinuza** [drgullin/icheck#36]
iCheck will not forward events when using event delegation, check this for reference:

Regular inputs:

http://codepen.io/anon/pen/dcIoh

iCheck inputs:

http://codepen.io/anon/pen/ktyvG

iCheck needs to forward those events to the underlying input

**Comment by drgullin** [comment]
iCheck doesn't support `click` event on inputs because of the nested labels support (inputs directly inside labels and labels inside labels).
You may use [callbacks](https://github.com/damirfoy/iCheck#callbacks) and [methods](https://github.com/damirfoy/iCheck#methods) instead.

**Comment by shinuza** [comment]
This impairs iCheck capabilities of being a drop in replacement for regular inputs

**Comment by joangrigorov** [comment]
I support shinuza's comment. We also have much problems with this. We have a lot of plug-ins that use the classic change event and if we update all plugins (which is not a quick job) we end up with plugins depending on iCheck, which is not good.

**Comment by kasperisager** [comment]
Any news on this?

**Comment by drgullin** [comment]
Prepared for the next version.

**Comment by kasperisager** [comment]
:thumbsup:
