### ISSUE TITLE
Add support for indeterminate (partially checked) state

### ISSUE THREAD

**Issue by ragulka** [drgullin/icheck#38]
HTML5 allows specifying indeterminate property for checkboxes. It would be great if iCheck also supported it: http://css-tricks.com/indeterminate-checkboxes/

**Comment by evil-shrike** [comment]
+1
it's highly needed

**Comment by DevDavido** [comment]
+1

**Comment by drgullin** [comment]
Indeterminate state support is added in https://github.com/fronteed/iCheck/commit/66ccc2795d085a10d0d73c9a6e506d266aade6a8
