### ISSUE TITLE
iCheck does no trigger change event

### ISSUE THREAD

**Issue by jaimestuardo** [drgullin/icheck#381]
Hello...

I have placed a checkbox in the header row of a grid. The fact is that by clicking that checkbox, all checkbox in the grid rows should if checked.

When normal checkbox, it works, but if I change it to iCheck, it does not. It seams iCheck does not trigger change event to the original checkbox.

Cheers
Jaime

**Comment by lorrandavid** [comment]
@jaimestuardo have you tried any of the callbacks provided by iCheck? like `ifChanged` or `ifClicked`? iCheck does not behave like a regular checkbox do, you can read about the callbacks [here](https://github.com/fronteed/icheck#callbacks).

**Comment by drgullin** [comment]
Fixed in v1.0.3 https://github.com/dargullin/icheck/commit/6f311edd715b1e8936419fccb2de17efa9948255.
