### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by xerwate** [drgullin/icheck#40]
I want to thank you for so beautiful plugin. But it is difficult to set up.

Why have not you made ​​a small guide how to set up? I have spent 2 days with no luck.

Thanks in advance!

**Comment by drgullin** [comment]
There's already nearly the same issue https://github.com/fronteed/iCheck/issues/19

**Comment by xerwate** [comment]
I found out where I failed. Must always include the main jQuery file.

```
< link href="css/skins/line/grey.css" rel="stylesheet"
< script src="js/jquery.js"></script>
< script src="js/jquery.icheck.js"></script>
```

But your guide is as follows

```
< link href="css/skins/line/grey.css" rel="stylesheet">
< script src="js/jquery.icheck.js"></script>
```

**Comment by drgullin** [comment]
Thanks, I've added additional info to the skin installation guide.
