### ISSUE TITLE
on function click

### ISSUE THREAD

**Issue by sabirnoor** [drgullin/icheck#400]
Hello developer,
Hope you are doing well..
i am facing some issue onload icheck click trigger for example:-
this is my function and what i am trying to do...
function resetfilter() {
        $('.filtercheckbox').each(function() {
               var isChecked = $(this).is(':checked');
               if(isChecked == true) { 
                     $(this).trigger('click')/// this case trigger not working with iCheck. can you suggest me how to execute trigger function onclick=" resetfilter()" this function
               }
        });
}

please reply me as soon as possible.
thanks
regards,
sibo (India)

**Comment by drgullin** [comment]
@sabirnoor you should trigger iCheck methods instead of `click` 
https://github.com/dargullin/icheck#methods
