### ISSUE TITLE
Uncheck radio button on second click...

### ISSUE THREAD

**Issue by BN83** [drgullin/icheck#402]
I have 2 radio buttons next to each other and they work great, however once you have checked one, there is no way to remove it other than reloading the page. Is it possible to click a checked radio button to uncheck it?

**Comment by hibobby** [comment]
$('.i-checks').on('ifClicked', function(event){
            if( $(event.target).is(':checked')){
                $(event.target).iCheck('uncheck');
            }else{
                $(event.target).iCheck('check');
            }
        });

**Comment by hibobby** [comment]
$('.i-checks').on('ifClicked', function(event){
            if( $(event.target).is(':checked')){
                $(event.target).iCheck('uncheck');
            }else{
                $(event.target).iCheck('check');
            }
        });
