### ISSUE TITLE
Any good forks?

### ISSUE THREAD

**Issue by cyphix333** [drgullin/icheck#413]
Have there been any good forks of this since it got abandoned? I've been trying and trying to find a replacement but can't seem to find an active good one; found a decent CSS based one, but you had to have specific markup with that, which isn't always possible, so that was out, then found another one where clicking the checkbox labels didn't work.

Going to have to stick to this until a new one is found.

**Comment by stevenvg** [comment]
is there anything that you needed that can't be achieved with this library in its current state?

**Comment by cyphix333** [comment]
Not really, which is why I continue to use it (for the time being); but it's never a good idea to attach yourself to something that has been abandoned.

**Comment by lorvent** [comment]
I am also looking...

bootstrap started providing some css based solutions but they are not as power as icheck ones.

**Comment by ernestosemedy** [comment]
It would be very niche if GH provided a tool to "compare" forks and see the ones who has more "activity"

**Comment by lorvent** [comment]
I was a big user of this package and i should say thanks to dev,
but now since bootstrap and many other packages started providing UI like this package, may be author lost interest.

but i didn't come across any package which has event listeners like this one.

**Comment by reiern70** [comment]
> I was a big user of this package and i should say thanks to dev,
> but now since bootstrap and many other packages started providing UI like this package, may be author lost interest.
> 
> but i didn't come across any package which has event listeners like this one.

Thanks for your answer. We has also being using this plugging for some time. Now we run into issues like "destroy" not properly working. We will have to decide if we fix that somehow on pklugin or use some workarounds in our application (or decide for other solutions)

**Comment by drgullin** [comment]
Hello everyone ✋ 

**iCheck is not died**.
It's been a while since I committed something to iCheck.
I'm back now to fix critical issues and to release iCheck v2.

**If you run into issues with iCheck, feel free to create an issue on Github.**
