### ISSUE TITLE
iCheck disabled checked

### ISSUE THREAD

**Issue by theveil2019** [drgullin/icheck#418]
Hi,
I have set default iCheck radio button to disabled. I'm using flat class green skin.
Now my problem is when i enable the radio button through jquery prop(), I am not able to see the green skin, instead it is in .disabled.checked mode. could any one help me on this issue. I've been trying to find a solution but all in vein. I'm cracking my head on this.

I know may be this is a simple fix, but it's not working for me. Appreciate any help

**Comment by drgullin** [comment]
You can't use `prop` method with iCheck, since it directly changes an attribute, without firing any callbacks (iCheck doesn't know is anything changed).
