### ISSUE TITLE
Problem when going back then forward.

### ISSUE THREAD

**Issue by rafatmyo** [drgullin/icheck#422]
When I select a radio button from my radio button options then go a page back and then go forward where I was, if I try to click  the option I clicked previously it it won't get selected. 
Has anyone had this issue?

**Comment by MarekOtruba** [comment]
you're not alone, don't be afraid :) i think that's a bug from the start

**Comment by justm** [comment]
Hello similar issue here. Have you find a solution or workaround for this?
I have ichecks on a first page (list view), when I go to second page (detail view) and then back to list view with browser back button, i have to click twice on an icheck to get it selected.  
Regards

**Comment by drgullin** [comment]
This will be fixed in v1.0.3.
