### ISSUE TITLE
Mac Safari iCheck won't render

### ISSUE THREAD

**Issue by acer152** [drgullin/icheck#423]
I have iCheck functioning properly in most browsers, however, they do not render properly on Mac Safari.  Can anyone help?

View this page in Chrome and Safari.  Chrome appears to function properly, but Safari shows regular looking checkboxes that do not function.  The icheck wrappers are applied, but not the style or functionality.

Note, this page is on temp server, and the rest of the site is protected behind login, so only this same page is available to review checkboxes.  You won't be able to click around, etc.  However, the icheck renders in Chrome but not Mac Safari.  Any help appreciated.

http://vicariousdesigns.com/misc/icheck.html

**Comment by drgullin** [comment]
Hello @acer152.
Something wrong with your code. Checkboxes at http://icheck.fronteed.com render successfully in Safari.

**Comment by acer152** [comment]
@fronteed - I've already checked that, and was hoping for help.

**Comment by drgullin** [comment]
@acer152 I see that iCheck works properly, but styles for checkboxes are missing.

**Comment by acer152** [comment]
All of the styles are there. What are you referring to?

On Sep 16, 2020, at 8:14 AM, Damir Sultanov <notifications@github.com> wrote:

﻿

@acer152<https://github.com/acer152> I see that iCheck works properly, but styles for checkboxes are missing.
