### ISSUE TITLE
IPAD icheck- checkbox not working

### ISSUE THREAD

**Issue by gmuruge1** [drgullin/icheck#424]
Hi,

IPAD icheck not working. It is not checked/unchecked. Working intermittently. Can anyone help to resolve this?

**Comment by gmuruge1** [comment]
Hi Team,

I'm using latest ios version 13.4.1.
the demo site itself working in iphone but not in ipad.
http://icheck.fronteed.com/

Anyone suggestions please?

**Comment by hanmi8** [comment]
I also faced the same problem.

It is also not selected in 'View desktop' on mobile devices.

I ask anyone to settle it. Please.

**Comment by magpie-imost** [comment]
iOS 13.4.1 has changed the default userAgent string so it will not be detected on _mobile
The string 'iPad' is missing. See. detail in [[Stack...](https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct)]
The solution is to adjust the detection for _mobile.
