### ISSUE TITLE
Can't uncheck by label in iOS

### ISSUE THREAD

**Issue by joeferraro** [drgullin/icheck#43]
Hi, thanks for the plugin. I'm running into an issue on iOS6 where tapping the label will not uncheck the checkbox. Is there a workaround?

**Comment by drgullin** [comment]
Works good for me, tested on ios6.
This issue happened in the previous version of iCheck, try to update plugin and clean browser's cache.

**Comment by joeferraro** [comment]
So, I have an event handler on my checkbox:

```
$('.filter').on('ifChanged', function(event){
     //do something here
});
```

If I remove this event handler, tapping the label to uncheck works.

**Comment by drgullin** [comment]
Can you show your HTML please? This works good on the demo page.

Unlike init and methods usage, callbacks should be binded directly to inputs, not to the parent blocks https://github.com/fronteed/iCheck/commit/97d02e400f8ef2921632defbd55837deef2da2e3
