### ISSUE TITLE
Callbacks not working on dynamically added checkboxes

### ISSUE THREAD

**Issue by Fvanraes** [drgullin/icheck#44]
I have to dynamically add checkboxes to a form, so i create the checkbox element, append it to my form and then initialize iCheck on it. This effectively turns the checkbox in an iCheck-style checkbox, but the callbacks are not working. 

```
// Dynamically add a checkbox
$('a.add-checkbox').on('click', function() {
    var input = '<input type="checkbox" id="mycheckbox" name="mycheckbox" />';
    $('form').append(input);

    $('#mycheckbox').iCheck({checkboxClass: 'icheckbox_flat-green',radioClass: 'iradio_flat-green'});
});

// This is not doing anything
$('#mycheckbox').on('ifChecked', function(event) {
    alert();
});
```

Note: The callbacks DO work on checkboxes that are already in the HTML on page load.

**Comment by drgullin** [comment]
This code won't work for the ajax-loaded inputs, since it's a replacement of `bind()`:

```
$('#mycheckbox').on('ifChecked', function(event) {
    alert();
});
```

Delegated events should be used instead:

```
$(document).on('ifChecked', '#mycheckbox', function(event) {
 alert('done'); 
});
```
