### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by fahadkhan82** [drgullin/icheck#46]
I am unable to get the value of selected checkbox or radio button and i haven't found any example as well related to this.

Thanks

**Comment by drgullin** [comment]
iCheck saves changes directly inside input elements, so you can work with them like you do without using this plugin:

``` js
$('input').val();
$('input').prop('checked');
```

**Comment by fahadkhan82** [comment]
Hi,

Really thanks for your prompt reply.

Thanks

**Comment by drgullin** [comment]
You're welcome.
