### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by drgullin** [drgullin/icheck#48]
Allow linking inside labels.

**Comment by ghost** [comment]
+1 on this. Links that are inside labels can not be clicked any longer.

**Comment by ChezFre** [comment]
Hey guys,

I've made a quick fix for this. It's not the most optimal code, but I needed something that would work quickly.

In "jquery.icheck.min.js" look for line 161 where the label events are coupled. On line 171 there's a check to see if it's a click event. Add the following code before the operate call.

This code will check if the clicked element is an anchor and open it in a new window or the same window based on your html.

``` javascript
var target = $(event.target),
    href = target.attr('href');

if( typeof href !== "undefined" && href.length > 0) {
  if( href.attr('target') == "_blank") {
    window.open( href );
  } else {
    window.location = href;
  }
} 
```
