### ISSUE TITLE
label

### ISSUE THREAD

**Issue by hotgeart** [drgullin/icheck#5]
Hi,

On Chrome with a label we can't uncheck the chexbox.

WORK :

<form>
    <input type="checkbox" value="1">
</form>

NOT WORK :

<form>
    <label><input type="checkbox" value="1"></label>
</form>

**Comment by drgullin** [comment]
Unchecking through label works fine in Chrome and Chrome Mobile.

**Comment by hotgeart** [comment]
Look : http://jsfiddle.net/AFZYt/

You can't uncheck with chrome

**Comment by drgullin** [comment]
fixed in v0.8 https://github.com/fronteed/iCheck/commit/fd3993f4e514a61ea6ae6a9cbe35faad66789576
