### ISSUE TITLE
Performance (with large number of radios)

### ISSUE THREAD

**Issue by linuxd3v** [drgullin/icheck#55]
I have a table with about 400 rows, 4 radios in each row.  
It takes about 30 seconds to convert them into icheck checkboxes....  

While when I reduce a number to 60 rows with 4 radios in each - 1 second is all it takes.  

So - something is disproportionately hogging performance there - I have no idea what exactly.... It does work  faster in firefox though (10 seconds).... soo. not sure what to make of all tihs...

**Comment by felixjet** [comment]
Maybe you should implement another way to do this, for example, view only the checkboxes from the current view and lets say, 20 rows before and after. For example, if you are viewing rows 120-140 (what fills on screen), let icheck use his magic only in the checkboxes from 100 to 160. The others, just remove() them. Put a on scroll event on the page and invoke new iChecks() as needed.

Or..... paginator!

**Comment by drgullin** [comment]
2.x version got a huge performance boost, check it out - https://github.com/fronteed/iCheck/tree/2.x-beta

It's memory-safe, binds only a few events and has a quite small number of function calls.
It also cares about reflows/repaints and uses mostly a native functions instead of jQuery's slower alternatives. 

I've made some calculations, customization of 1000 inputs takes 0.5s - 1s time.

**Comment by genechuah** [comment]
We implemented 1.x but now we have 2000+ records that each have an iCheck checkbox. Doing $('.checkbox').iCheck('check') takes forever, possibly up to a full minute. Is v2.x fully backwards-compatible? Is there a way to speed up this operation? Thank you.

**Comment by iamsolarplexus** [comment]
I ran into this as well but wasn't able to get 2.0 working.  So no, I don't believe it's fully backwards-compatible.  I'm listening to this script's development feed in the hopes that eventually development will pick up again or there will be a demo of 2.0 somewhere.  Haven't had the time to look into it myself.

**Comment by mubbashar** [comment]
is 2.0 working? i tried to test it but was not able to get it working
