### ISSUE TITLE
How to get this to work :)

### ISSUE THREAD

**Issue by Strutsagget** [drgullin/icheck#56]
Hi 
Your script looks really great but I'm wondering how to get this to work.

I have jquery 1.7 running
I have jquery.icheck.js running.
I have added the start script inside my header.

```
$(document).ready(function(){
  $('input').iCheck({
    checkboxClass: 'icheckbox_minimal',
    radioClass: 'iradio_minimal',
    increaseArea: '20%' // optional
  });
});
```

I want to add my own styles so i just want the div to appear around the input and then hide the input.

But nothing happens. :/
Ok got it to start working with Drupal by changing the script to

```
jQuery(document).ready(function(){
  jQuery('input').iCheck({
    checkboxClass: 'icheckbox_minimal',
    radioClass: 'iradio_minimal',
    increaseArea: '20%' // optional
  });
});
```

**Comment by drgullin** [comment]
Seems you've fixed this.
