### ISSUE TITLE
Conflict with Bootstrap

### ISSUE THREAD

**Issue by ghost** [drgullin/icheck#57]
Hello, been using bootstrap for quite a while now, so i decided to add iCheck. iCheck works perfect but breaks down Bootstrap. Botht the jQuery and the Zepto versions :: however i discovered that if you put the zepto version just before jQuery script it could work. Any idea?

**Comment by drgullin** [comment]
iCheck works with Bootstrap https://github.com/fronteed/iCheck/issues/70
