### ISSUE TITLE
Select all

### ISSUE THREAD

**Issue by ivanionut** [drgullin/icheck#58]
Hello,
how can I do a "select all"?

I tried that, but it does not work:

``` javascript
$(document).ready(function () {
    $("#ckbCheckAll").click(function () {
        $(".checkBoxClass").prop('checked', $(this).prop('checked'));
    });
});
```

**Comment by padaVVan** [comment]
``` javascript
$(document).ready(function() {
  $('#ckbCheckAll')
    .on('ifChecked', function(event) {
        $('.checkBoxClass').iCheck('check');
    })
    .on('ifUnchecked', function() {
        $('.checkBoxClass').iCheck('uncheck');
    });
  });
```

**Comment by ivanionut** [comment]
I tried, but it does not work:

http://goo.gl/4vbQP

**Comment by padaVVan** [comment]
But you are using a different class for checkBox element. Here is the error.

``` JavaScript
$('.checkBoxClass').iCheck('check');
//replace on
$('.checksearch').iCheck('check');
```

Here a working version http://jsbin.com/eyezef/5/

I use the translate.google.com to translate text.

**Comment by ivanionut** [comment]
Ok, very good! Thank you!

But I would like to make it so that deselecting an item, you also uncheck "Select all". Like this: http://jsfiddle.net/ivanionut/N7uYR/

How can I do?

**Comment by drgullin** [comment]
Here's the example http://jsfiddle.net/N7uYR/1/

**Comment by ivanionut** [comment]
If I select "Check Box 1", "Check Box 2", "Check Box 3", "Check Box 4" is not selected, "Select all"

Like this: http://jsfiddle.net/ivanionut/N7uYR/

**Comment by drgullin** [comment]
There's no iCheck instance in your example.

**Comment by ivanionut** [comment]
Sure.

But it's just an example of what I should do. I want to do the same thing, using iCheck.

**Comment by drgullin** [comment]
That's pretty easy:

``` js
$('input.check').on('ifChecked', function(event) {
  // check if all the '.check' inputs are checked => $('input.all').iCheck('check');
});
```
