### ISSUE TITLE
problem with checkbox and radio inside label

### ISSUE THREAD

**Issue by rumends** [drgullin/icheck#6]
when you put checkbox or radio inside label element (with for="id" or without) changing element status not working.

when I change your example like this:

&#60;&#108;&#105;&#62;&#10;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#60;&#108;&#97;&#98;&#101;&#108;&#62;&#60;&#105;&#110;&#112;&#117;&#116;&#32;&#116;&#97;&#98;&#105;&#110;&#100;&#101;&#120;&#61;&#34;&#49;&#34;&#32;&#116;&#121;&#112;&#101;&#61;&#34;&#99;&#104;&#101;&#99;&#107;&#98;&#111;&#120;&#34;&#32;&#105;&#100;&#61;&#34;&#109;&#105;&#110;&#105;&#109;&#97;&#108;&#45;&#99;&#104;&#101;&#99;&#107;&#98;&#111;&#120;&#45;&#49;&#34;&#62;&#10;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#67;&#104;&#101;&#99;&#107;&#98;&#111;&#120;&#32;&#49;&#60;&#47;&#108;&#97;&#98;&#101;&#108;&#62;&#10;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#60;&#47;&#108;&#105;&#62;&#10;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#60;&#108;&#105;&#62;&#10;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#60;&#108;&#97;&#98;&#101;&#108;&#32;&#102;&#111;&#114;&#61;&#34;&#109;&#105;&#110;&#105;&#109;&#97;&#108;&#45;&#99;&#104;&#101;&#99;&#107;&#98;&#111;&#120;&#45;&#50;&#34;&#62;&#60;&#105;&#110;&#112;&#117;&#116;&#32;&#116;&#97;&#98;&#105;&#110;&#100;&#101;&#120;&#61;&#34;&#50;&#34;&#32;&#116;&#121;&#112;&#101;&#61;&#34;&#99;&#104;&#101;&#99;&#107;&#98;&#111;&#120;&#34;&#32;&#105;&#100;&#61;&#34;&#109;&#105;&#110;&#105;&#109;&#97;&#108;&#45;&#99;&#104;&#101;&#99;&#107;&#98;&#111;&#120;&#45;&#50;&#34;&#62;&#10;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#67;&#104;&#101;&#99;&#107;&#98;&#111;&#120;&#32;&#50;&#60;&#47;&#108;&#97;&#98;&#101;&#108;&#62;&#10;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#60;&#47;&#108;&#105;&#62;

nothing happens when click on checkbox or label.
I try it in IE, Firefox and Chrome.

**Comment by Ph3nol** [comment]
I have the same problem. Any idea about it?

Thanks.

**Comment by viktordavidovich** [comment]
GUYS, why this plugin, do not support mousedown and mouseup event, look default checkbox and radiobuttons in browers. (

**Comment by drgullin** [comment]
@viktordavidovich, create a separate ticket and provide a detailed information about the issue, please.

**Comment by drgullin** [comment]
fixed in v0.8, https://github.com/fronteed/iCheck/commit/fd3993f4e514a61ea6ae6a9cbe35faad66789576

even nested labels now can be used, like:

``` html
<label>
  <input type="radio" id="foo">
  <label for="foo">Bar</label>
</label>
```
