### ISSUE TITLE
Problem with ajaxs checkbox

### ISSUE THREAD

**Issue by rumends** [drgullin/icheck#60]
When I use methods from issue #37 there is a little problem whit this delegation.
If you use

```
$('#mycheckbox').on('ifToggled', function(){
// custom function
});
```

to bind custom function to specific checkbox after ajaxs trigger 'icheck' there is no bind function to `$('#mycheckbox')`
Is there any solution for this?

**Comment by drgullin** [comment]
Try this code:

```
$(document).on('ifToggled', '#mycheckbox', function(){
// custom function
});
```

This should handle also the ajax loaded inputs.
