### ISSUE TITLE
Suggestion: Release on CDNJS.com

### ISSUE THREAD

**Issue by refringe** [drgullin/icheck#64]
CDNJS is a free Content Delivery Network hosted by CloudFlare for open source, community-driven projects. It would be great to release the minified versions of iCheck on CDNJS for all to use.

Instructions to add a project to CDNJS:
https://github.com/cdnjs/cdnjs

Node is required to test the fork before the pull request is accepted. If anyone has experience with node, your help would be very much appreciated.

**Comment by wmh** [comment]
@fronteed Please add a tag to current version, and I'll do the rest.

``` sh
git tag 0.9.1
git push --tags
```

**Comment by drgullin** [comment]
@wmh done, can you do the rest? The actual tag is 1.0.1

**Comment by wmh** [comment]
Thanks @fronteed 
iCheck v1.0.1 is now on the way to cdnjs.com
https://github.com/cdnjs/cdnjs/pull/2368

**Comment by wmh** [comment]
The branch has been merged.

**Comment by drgullin** [comment]
Thanks @wmh :+1:
