### ISSUE TITLE
Support for dynamically generated input elements

### ISSUE THREAD

**Issue by ijmorgado** [drgullin/icheck#66]
Hi!

I read the docs a few days ago...I was trying to use this great jquery plugin in a project but I was generating checks and radios dynamically and I didn't figured out how to do that without modify the core of the plugin.

**Comment by drgullin** [comment]
``` html
<div class="dynamic">
   some <inputs>
</div>
```

Just call the iCheck once more on a dynamically loaded content:

``` js
$('.dynamic').iCheck();
```

Boom, it works.

**Comment by ambasador** [comment]
ok thx
