### ISSUE TITLE
Touch doesn't appear to work with HP Envy 2

### ISSUE THREAD

**Issue by tonyhawe** [drgullin/icheck#67]
Using a HP Envy 2 and chrome nothing seems to happen when touching the checkbox.
Clicking using the trackpad works fine.

Touching it in IE works fine.

IE 8
Chrome 28.0.15

**Comment by drgullin** [comment]
HP Envy 2 is a Windows 8 tablet, iCheck will start supporting pointer events API from the next version.

**Comment by drgullin** [comment]
This issue is fixed in 2.x version https://github.com/fronteed/iCheck/tree/2.x-beta
