### ISSUE TITLE
iCheck + MySql

### ISSUE THREAD

**Issue by rmngomes** [drgullin/icheck#74]
Hi,

I´m having problems with the mysql/php integration and iCheck.

I can retrive the values from db, change the values to checked if needed (via db) but when i update the values, somehow they are always duplicated in the db column.

Without using mysql everything seems to be ok.

I´ve already set the ajax cache optin for false, but the problem remains.

Ps - i´m doing the update via ajax, and using the map(function () {    return this.value;

**Comment by drgullin** [comment]
That's not the iCheck issue.
