### ISSUE TITLE
Checked fields passed as false

### ISSUE THREAD

**Issue by khanh703** [drgullin/icheck#79]
Any checkbox that are 'checked' are not getting posted. When I check on a checkbox, the "checked" class is added to the wrapper div, but the input tag does not have a 'checked' attribute appended.

Edit: Checkboxes that are not 'iCHeck'ed are correctly posting. 'iCheck'ed checkboxes are not posting.

**Comment by drgullin** [comment]
All checked checkboxes and radio buttons are getting posted.
Chrome web developer tools and Firebug doesn't show changes for a `checked` state.
