### ISSUE TITLE
Is there support events mouseup mousedown? 

### ISSUE THREAD

**Issue by viktordavidovich** [drgullin/icheck#8]
Very often, the need to have multiple states checkbox:
1) Checked
2)Unchecked
3)Disabled
4)onmousedown
5)onmouseup

on the demo page, i didn't see this effect(mousedown mouseup) something like default checkbox or radiobutton(without your plugin). You understand my quastion? Sorry for my bad english :(
![checkbox](https://f.cloud.github.com/assets/2580044/328874/51433e16-9ba6-11e2-9628-a7ceeff01e08.png)
Look picture first line:
1) we have 3 different states checkbox : normal , onmouseup , onmousedown.

**Comment by drgullin** [comment]
> i didn't see this effect(mousedown mouseup)

That's an active state, try to use `activeClass` option. It's appended as a class on `mousedown` and removed on `mouseup`. Touch events are also supported.

**Comment by viktordavidovich** [comment]
Thank's man:D Just i don't see this effect on your demo site  :+1:
Have a nice day!
