### ISSUE TITLE
Multiple "ifChanged" events fired when changing a radio input selection

### ISSUE THREAD

**Issue by bob6664569** [drgullin/icheck#80]
When changing the initial selection of the radio input : 
- A first event is fired with the previous selection unchecked (=> no more value for the whole field, like if no radio input was checked anymore)
- A second event is fired with the new selection which became active (=> the only correct one that must be triggered, like this is the case with a standard radio input and his "onchange" event)

**Comment by drgullin** [comment]
This is how `ifChanged` callback works. You may try to use `ifToggled`, `ifChecked` or `ifUnchecked` instead.

`ifChanged` callback will probably be dropped in the next version, due to organization specifity.

**Comment by bob6664569** [comment]
Ok, thank you for your answer. 
Still, in my opinion, it would be greatly appreciated that the enhanced control just behaves like the original one in the DOM to avoid this kind of mistakes.

**Comment by ekayir** [comment]
ifChecked  works for me. Thanks.
