### ISSUE TITLE
checkbox to behave like radio button

### ISSUE THREAD

**Issue by ghost** [drgullin/icheck#81]
I have a question not sure how to solve it

i have the following generated automatic 

``` javascript
<div class="group01">
<input type="checkbox" value="1" name="foo[]"  class="{the_only_thing_i_can_change}"/>
<input type="checkbox" value="2" name="foo[]"  class="{the_only_thing_i_can_change}"/>
</div>
<div class="group02">
<input type="checkbox" value="unicorns" name="foo[]"  class="{the_only_thing_i_can_change}"/>
<input type="checkbox" value="oliphants" name="foo[]"  class="{the_only_thing_i_can_change}"/>
</div>
```

is it possible to have both groups to behave like a 'radio' button 
example: user will be able to check one from group01 and check one button from group02

?
Thanks!

**Comment by RichardOtvos** [comment]
Hey there!
I found this StackOverflow answer that might work for you: 
http://stackoverflow.com/questions/5839884/make-checkbox-behave-like-radio-buttons-with-javascript

You have to modify this a bit for groups, but the theory is the same. You might also have to call iCheck too, besides making the checkbox cehcked, but I'm not sure. 

If you still have questions, just write it here, I will be happy to help you.

**Comment by drgullin** [comment]
That's possible, see the link to stackoverflow.
