### ISSUE TITLE
Radio button and Check boxes touch event is malfunctioning in Google chrome ,windows 7 tablet

### ISSUE THREAD

**Issue by madhank** [drgullin/icheck#87]
I tested the plugin in Google chrome, windows 7 tablet. It is malfunctioning as I am not able to check any radio buttons and check boxes for touch event

**Comment by cybernet** [comment]
leave a link. i want to test it on android

**Comment by madhank** [comment]
It works on android, google chrome. You can test it using iCheck website website http://fronteed.com/iCheck/

**Comment by drgullin** [comment]
Newer version supports the pointer events (full support of the newest Windows tablets).

You can already check the hover/active/focus states https://github.com/fronteed/iCheck/blob/2.x-beta/icheck.js

**Comment by madhank** [comment]
Dear Damir,

Thank you for replying. We would love to be connected with you and help give feedback on this plugin when persist.

Regards,
Madhan

**Comment by drgullin** [comment]
2.x version supports both `pointer` and `MSPointer` events.
