### ISSUE TITLE
label and checkbox can't display in one line

### ISSUE THREAD

**Issue by rainyin** [drgullin/icheck#88]
when i use it according to the demo, not include the custom.css
I find the lable just display under the checkbox or radio

**Comment by benjamincharity** [comment]
iCheck hides the checkbox or radio button and inserts a `<div>` which acts as the checkbox or radio button. Browsers set all `<div>`'s to `display: block;` by default. So you will need to target the `<div>` and set it to `display: inline-block` to allow other elements to display next to it.
