### ISSUE TITLE
Trigger change event to be a real drop-in customization

### ISSUE THREAD

**Issue by stof** [drgullin/icheck#89]
Applying the iCheck plugin on a radio button will break any other JS code relying on the change event being triggered when the value of the radio changes. To be easier to use, it would be a good idea to trigger the change event when the change occurs through the improved interface.

**Comment by stof** [comment]
I found a workaround:

``` js
    $input.on('ifChanged', function (event) {
        $(event.target).trigger('change');
    });
```

Supporting it in the plugin itself would make it easier to use though

**Comment by amsaid** [comment]
+1

**Comment by drgullin** [comment]
2.x version supports direct event bindings https://github.com/fronteed/iCheck/tree/2.x-beta
