### ISSUE TITLE
unchecked class

### ISSUE THREAD

**Issue by oozrafa** [drgullin/icheck#9]
Hey. I was wondering if it's possible to add 'uncheckedClass' . So that when the plugin initializes it will either add the 'uncheckedClass' or 'checkedClass', depending on the state of the original input.

Also is it possible to have a separate  'checkedClass' and 'uncheckedClass' for radio buttons and checkboxes?

This also means that the callbacks need to be per input type.

Basically this is because I want to use font-awesome classes instead of images.

also, if you have a better solution to use font awesome instead of background images (sprite) then that would be greatly appreciated.

**Comment by drgullin** [comment]
I've added 10 new options for the tasks like this one
https://github.com/fronteed/iCheck#options

The ones you asked for: `checkedCheckboxClass, checkedRadioClass, uncheckedCheckboxClass, uncheckedRadioClass`.

**Comment by oozrafa** [comment]
Amazing. Thanks!
