### ISSUE TITLE
Cannot change value programmaticly

### ISSUE THREAD

**Issue by LoicMahieu** [drgullin/icheck#91]
If the value of the checkbox is changed after the page load, iCheck does refresh the UI.

Example: http://jsfiddle.net/sp4A2/

I know:
$('input').iCheck('check'); — change input's state to checked
$('input').iCheck('uncheck'); — remove checked state
$('input').iCheck('toggle'); — toggle checked state

But it's very annoying when dealing with vendors library. It would be great if iCheck response to standard html events.

**Comment by drgullin** [comment]
2.x version supports standard events https://github.com/fronteed/iCheck/tree/2.x-beta
