### ISSUE TITLE
Scroll bar not visible in the jQuery UI dialog

### ISSUE THREAD

**Issue by arindamdc** [drgullin/icheck#92]
Browser: Firefox v25
I have a form which has controls (textarea) on which the scroll bar is working correctly. I also have a modal dialog on this form which also has controls (textarea), but the scroll bar is not visible. The scroll bar is initialising correctly (zoom on double click feature is working correctly), but the scroll bar and rail is not visible.

Any ideas...

**Comment by drgullin** [comment]
This isn't the iCheck issue.
