### ISSUE TITLE
Indeterminate state not shown

### ISSUE THREAD

**Issue by hsz** [drgullin/icheck#94]
If I set `indeterminate` state to my checkbox with:

```
$('input:checkbox').iCheck('indeterminate');
```

its parent gets `indeterminate` class but there nothing happens.

Is it possible to create new state in `.png` assets with hyphen for example ?

**Comment by drgullin** [comment]
None of the available skins support indeterminate state, since this feature is rarely used.

**Comment by hsz** [comment]
@fronteed Maybe indeterminate state is rarely used because none of the available skins support it ? ;-)

**Comment by mtarnovan** [comment]
@fronteed I think this would be a very useful feature, maybe for 2.0. It shouldn't be that difficult to add an indeterminate state to some skins (à la Gmail `[-]`). What do you think?
