### ISSUE TITLE
300ms delay on Safari in iOS

### ISSUE THREAD

**Issue by jonobobo** [drgullin/icheck#95]
Any chance the click event could fire on touchend instead of click when in a mobile browser?  That typical 300ms delay is annoying when working with large checkbox lists, and this plugin doesn't play too well with polyfills like [FastClick](https://github.com/ftlabs/fastclick)

**Comment by drgullin** [comment]
iCheck 2.x has a "fastclick" option out of the box, its name is `tap`. If set to `true`, inputs state is changed directly after touchend/pointerup events (Windows tablets and phones are also supported), without 300ms "click delay".

iCheck 2.x is also compatible with the Fastclick plugin - https://github.com/ftlabs/fastclick, but doesn't require it.
