### ISSUE TITLE
Preserving tooltips/titles for checkboxes

### ISSUE THREAD

**Issue by deanbolton** [drgullin/icheck#96]
Firstly, great plugin. Thank you!

Question... is it possible to preserve tooltips for checkboxes? The title is set in the original markup but not referenced/used/applied when this plugin works its magic and transforms a checkbox.

**Comment by drgullin** [comment]
Attribute inheritance would be a nice feature, thanks.
I think this should be supported out of the box.

You can do it right now using `ifCreated` callback:

``` js
$('input').on('ifCreated', function(event) {
  if (this.title) {
    $(this).parent().attr('title', this.title);
  }
});
```

**Comment by deanbolton** [comment]
Again, thank you! That's what I was looking for. I'm new to all this, so I've included code with complete syntax for my fellow noobs.

```
$('input').on('ifCreated', function(event) {
    if ($(this).attr('title')) {
        $(this).parent().attr('title', $(this).attr('title'));
    }
});
```

**Comment by drgullin** [comment]
iCheck 2.x supports `inherit` option https://github.com/fronteed/iCheck/tree/2.x-beta, that can be used to inherit any attribute.
